using Photon.Pun;
using System.Collections;
using UnityEngine;
using UnityEngine.InputSystem;

public class InteractableObject : MonoBehaviourPunCallbacks
{
    private PhotonView view;
    public InputActionReference inputAction;
    private Animator anim;
    public DropObject dropObj;

    public string ID;
    private bool isFinish = false;

    private void Start() {
        view = GetComponent<PhotonView>();
        anim = GetComponent<Animator>();
        dropObj = GetComponent<DropObject>();

        if (string.IsNullOrEmpty(ID)) {
            ID = "CanInteract_" + gameObject.name;
        }
        //ТСЅ»»ҐѕНПъ»Щ
        if (StateManager.instance.GetInteractState(ID)) {
            isFinish = true;
            Destroy(gameObject);
        }
        //ЖфУГinputAction
        if (inputAction != null && inputAction.action != null) {
            inputAction.action.Enable();
        }
    }
    private void Update() {
        if (IsFindPlayer() && inputAction.action.WasPressedThisFrame()&&!isFinish) {
            if (isFinish) return;
            Debug.Log("Ѕ»»Ґ");
            //ЗлЗуЅ»»Ґ
            StateManager.instance.RequestInteract(ID);
            StartCoroutine(OpenChest());
        }
    }
    //јмІвёЅЅьКЗ·сНжјТ
    private bool IsFindPlayer() {
        float Range = 2f;
        Collider[] player = Physics.OverlapSphere(transform.position, Range);
        foreach (Collider c in player) {
            if(c.CompareTag("Player")) return true;
        }
        return false;
    }
    //ІҐ·Е ±¦ПдїЄЖф¶Ї»­
    private IEnumerator OpenChest() {
        view.RPC("RPC_ChestAnim",RpcTarget.All);

        //µИґэ¶Ї»­
        yield return new WaitForSeconds(1f);
        //µфВдОп
        dropObj.DropOccur(transform.position);
        Interacted();
    }
    //Пъ»Щ
    private void Interacted() {
        if (PhotonNetwork.IsMasterClient) {
            Debug.Log("Destory IntectableObject");
            PhotonNetwork.Destroy(gameObject);
        } else {
            view.RPC("RPC_Destory", RpcTarget.MasterClient);
        }
    }
    [PunRPC]
    private void RPC_Destory() {
        isFinish = true;
        PhotonNetwork.Destroy(gameObject);
    }
    [PunRPC]
    private void RPC_ChestAnim() {
        anim.SetTrigger("open");
    }
}
